# https://github.com/dexpota/kitty-themes

#theme
include ./themes/Cobalt2.conf
inactive_text_alpha 0.8
background_opacity 0.95

# font_family 
font_family     family="JetBrains Mono"
italic_font      auto 
bold_font        auto 
bold_italic_font auto 

font_size        12.0 

symbol_map U+23fb-U+23fe,U+2665,U+26a1,U+2b58,U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b5,U+e700-U+e7c5,U+ea60-U+ec1e,U+ed00-U+efc1,U+f000-U+f2ff,U+f300-U+f372,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font

cursor_blink_interval 0

# layout
strip_trailing_spaces smart

sync_to_monitor yes

# Window layout
remember_window_size no
initial_window_width 900
initial_window_height 600
window_padding_width 12
hide_window_decorations no

# enabled_layouts 
enabled_layouts splits,stack
map f1 toggle_layout stack
map f5 launch --cwd=current --location=hsplit
map f6 launch --cwd=current --location=vsplit

# Tab bar
tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_bar_min_tabs 2
tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370} ({index} {tab.active_oldest_exe}) {tab.active_wd.replace('/Users/rockyzhang', '~')} {fmt.fg._5c6370}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._baa0e8}{fmt.bg.default}{fmt.fg.default}{fmt.bg._baa0e8} ({index} {tab.active_oldest_exe}) {tab.active_wd.replace('/Users/rockyzhang', '~')} {fmt.fg._baa0e8}{fmt.bg.default} "
active_tab_font_style bold

# open new tab with cmd+t
map cmd+t new_tab_with_cwd

# new split with default cwd
map cmd+shift+d new_window

allow_remote_control yes

term xterm-256color

# key bindings
clear_all_shortcuts yes

map ctrl+c        copy_to_clipboard
map ctrl+v        paste_from_clipboard
map shift+insert paste_from_clipboard

map ctrl+shift+t new_tab
map ctrl+shift quit

map ctrl+alt+d launch --location=hsplit --copy-env
map ctrl+alt+r launch --location=vsplit --copy-env

map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right

map kitty_mod+up move_window up
map kitty_mod+down move_window down
map kitty_mod+left move_window left
map kitty_mod+right move_window right
