
backend = "glx";
vsync = true;

use-damage = true;
unredir-if-possible = true;

fading = true;
fade-in-step = 0.05;  
fade-out-step = 0.05;
fade-delta = 6;        

shadow = true;
shadow-radius = 12;    
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.40;

shadow-exclude = [
    "window_type = 'desktop'",
    "window_type = 'dock'",
    "_GTK_FRAME_EXTENTS@:c"
];

blur: {
    method = "dual_kawase";
    strength = 3;  
    background = true;
    background-frame = false;
    background-fixed = false;    
};

blur-background-exclude = [
    "window_type = 'desktop'",
    "window_type = 'dock'",       
    "_GTK_FRAME_EXTENTS@:c"
];

opacity-rule = [
    "95:class_g *?= 'Alacritty'",
    "95:class_g *?= 'dunst'",
    "100:class_g = 'xsetroot'"
];

corner-radius = 12;
round-borders = 1;
rounded-corners-exclude = [
    "window_type = 'desktop'",
    "window_type = 'dock'",
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
];

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.85; focus = true; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.95; shadow = false; blur-background = false; }
  dropdown_menu = { opacity = 0.95; shadow = false; blur-background = false; }
};
