[manager]
prepend_keymap = [
# Open a terminal in the current folder by pressing the T key
	{ on = [ "t" ], run = 'shell "$SHELL" --block', desc = "Open shell here" },
	
	# Show/hide hidden files on "zh" 
	{ on = [ "z", "h" ], run = "hidden toggle", desc = "Toggle hidden files" },

	# Quickly create a file with "n" and a folder with "N"
	{ on = [ "n" ], run = "create", desc = "Create a file or directory" },
	
# Bulk rename to "r"
	{ on = [ "r" ], run = "rename --cursor=before_ext", desc = "Rename a file" }
]
