[manager]
ratio          = [ 1, 3, 4 ] 
sort_by        = "name"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 4
max_width       = 1000
max_height      = 1000
cache_dir       = "~/.cache/yazi"

image_preview_delay = 15

[opener]
edit = [
	{ run = '${EDITOR:-vim} "$@"', block = true, for = "unix" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", for = "unix" }
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open" ] },
	{ mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "open" },
	{ mime = "video/*", use = "open" },
	{ mime = "audio/*", use = "open" },
	{ mime = "application/pdf", use = "open" },
	{ mime = "application/zip", use = "ouch" },
	{ mime = "application/x-tar", use = "ouch" },
	{ mime = "text/*", use = "code-glow" }
]

