[font]
size = 13

[font.bold]
family = "Terminess Nerd Font"

[font.bold_italic]
family = "Terminess Nerd Font"

[font.italic]
family = "Terminess Nerd Font"

[font.normal]
family = "Terminess Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action= "Paste"},]

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[bell]
animation = "EaseOutExpo"
color = "#e4c9af"
duration = 1

[window]
opacity = 1.0
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns=80
lines=24

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[terminal]