
[general]
import = [
    "~/.config/alacritty/themes/Cobalt2.toml"
]

[window]
padding = { x = 20, y = 20 }
opacity = 0.90 

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Font"
style = "Italic"

[selection]
save_to_clipboard = true


